# Generated by Django 4.2.23 on 2025-07-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptchaChallenge',
        ),
    ]
