# Generated by Django 4.2.23 on 2025-09-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptchaChallenge',
        ),
    ]
