# Generated by Django 4.2.25 on 2025-10-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0004_delete_captchachallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='animations/')),
                ('description', models.TextField(help_text='Describe the scene in detail as you would to a blind person')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
